export interface AIHubTool {
  id: string;
  title: string;
  subtitle: string;
  description: string;
  icon: string;
  color: string;
  category: AIHubCategory;
  route: string;
  badge?: "AI" | "New" | "Popular";
  available: boolean;
}

export type AIHubCategory =
  | "assistants"
  | "wellness"
  | "personal"
  | "medical"
  | "mindfulness";

export const AI_HUB_CATEGORIES: {
  id: AIHubCategory;
  label: string;
  icon: string;
}[] = [
  { id: "assistants", label: "AI Assistants", icon: "psychology" },
  { id: "wellness", label: "Wellness", icon: "spa" },
  { id: "personal", label: "Growth", icon: "trending-up" },
  { id: "medical", label: "Medical", icon: "medical-services" },
  { id: "mindfulness", label: "Mindfulness", icon: "self-improvement" },
];

export const AI_HUB_TOOLS: AIHubTool[] = [
  // ── AI Assistants ─────────────────────────────────────────────────
  {
    id: "ai-mate",
    title: "AI Mate",
    subtitle: "Your 24/7 listener",
    description: "A kind, empathetic companion trained on mental health support for Liberia.",
    icon: "forum",
    color: "#3A7BD5",
    category: "assistants",
    route: "/(tabs)/ai-mate",
    badge: "Popular",
    available: true,
  },
  {
    id: "cbt",
    title: "CBT Assistant",
    subtitle: "Challenge unhelpful thoughts",
    description: "Cognitive Behavioural Therapy exercises to reframe negative thinking patterns.",
    icon: "psychology",
    color: "#7C5DB8",
    category: "assistants",
    route: "/cbt",
    badge: "New",
    available: true,
  },
  {
    id: "anxiety",
    title: "Anxiety Relief",
    subtitle: "Calm your anxious mind",
    description: "Evidence-based anxiety relief with guided exercises and personalized coping plans.",
    icon: "favorite",
    color: "#E07A5F",
    category: "assistants",
    route: "/anxiety",
    badge: "AI",
    available: true,
  },
  {
    id: "crisis",
    title: "Crisis Support AI",
    subtitle: "Immediate compassionate help",
    description: "Safe, immediate support when you're struggling most. Always connected to human help.",
    icon: "emergency",
    color: "#E03E3E",
    category: "assistants",
    route: "/(tabs)/support",
    badge: "AI",
    available: true,
  },
  {
    id: "gratitude",
    title: "Gratitude AI",
    subtitle: "Build a gratitude habit",
    description: "Daily guided gratitude reflections personalised to your life and mood.",
    icon: "volunteer-activism",
    color: "#6FCF97",
    category: "assistants",
    route: "/gratitude",
    badge: "New",
    available: true,
  },

  // ── Wellness ──────────────────────────────────────────────────────
  {
    id: "mood-insights",
    title: "Mood Analyzer",
    subtitle: "AI patterns in your moods",
    description: "See how your mood has shifted over time with AI-generated insights and trends.",
    icon: "insights",
    color: "#5C97E0",
    category: "wellness",
    route: "/mood-insights",
    badge: "AI",
    available: true,
  },
  {
    id: "daily-checkin",
    title: "Daily Check-in",
    subtitle: "Adaptive daily reflection",
    description: "A short, personalised check-in that adapts to your time of day and recent moods.",
    icon: "check-circle",
    color: "#3A7BD5",
    category: "wellness",
    route: "/daily-checkin",
    badge: "Popular",
    available: true,
  },
  {
    id: "affirmation",
    title: "Daily Affirmation",
    subtitle: "Words to start your day",
    description: "AI-crafted affirmations personalised to your name, goals, and current mood.",
    icon: "auto-awesome",
    color: "#6FCF97",
    category: "wellness",
    route: "/affirmations",
    badge: "AI",
    available: true,
  },
  {
    id: "wellness-report",
    title: "Wellness Report",
    subtitle: "Your full mental health picture",
    description: "A comprehensive AI report summarising your mood, sleep, journal, and risk trends.",
    icon: "assessment",
    color: "#7C5DB8",
    category: "wellness",
    route: "/mood-insights",
    badge: "New",
    available: true,
  },
  {
    id: "stress-tips",
    title: "Stress Coach",
    subtitle: "Quick coping ideas",
    description: "Context-aware stress management tips tailored to what you're experiencing right now.",
    icon: "tips-and-updates",
    color: "#E07A5F",
    category: "wellness",
    route: "/stress-tips",
    available: true,
  },

  // ── Personal Growth ───────────────────────────────────────────────
  {
    id: "journal",
    title: "AI Journal",
    subtitle: "Write and reflect with AI",
    description: "Journal freely and receive kind AI reflections, emotion detection, and insights.",
    icon: "edit-note",
    color: "#E0A800",
    category: "personal",
    route: "/journal",
    badge: "Popular",
    available: true,
  },
  {
    id: "goals",
    title: "Goal Tracker",
    subtitle: "Set and achieve wellness goals",
    description: "Set meaningful mental health goals and get AI-powered accountability check-ins.",
    icon: "flag",
    color: "#3A7BD5",
    category: "personal",
    route: "/goals",
    badge: "New",
    available: true,
  },
  {
    id: "productivity",
    title: "Productivity Coach",
    subtitle: "Do more, stress less",
    description: "AI coaching to help you structure your day, manage energy, and reduce overwhelm.",
    icon: "rocket-launch",
    color: "#5C97E0",
    category: "personal",
    route: "/productivity",
    badge: "New",
    available: true,
  },
  {
    id: "coping",
    title: "Coping Plan",
    subtitle: "Personalised coping strategies",
    description: "Receive a step-by-step coping plan based on what you're going through right now.",
    icon: "healing",
    color: "#6FCF97",
    category: "personal",
    route: "/coping-plan",
    badge: "AI",
    available: true,
  },
  {
    id: "smart-match",
    title: "Doctor Smart Match",
    subtitle: "Find the right specialist",
    description: "Describe your symptoms and get matched to the most relevant doctor in your county.",
    icon: "person-search",
    color: "#7C5DB8",
    category: "personal",
    route: "/smart-match",
    badge: "AI",
    available: true,
  },

  // ── Medical ───────────────────────────────────────────────────────
  {
    id: "symptom-check",
    title: "Symptom Check",
    subtitle: "Understand what you feel",
    description: "Describe your symptoms to get safe triage guidance before seeing a doctor.",
    icon: "health-and-safety",
    color: "#3A7BD5",
    category: "medical",
    route: "/symptom-check",
    badge: "AI",
    available: true,
  },
  {
    id: "sleep-coach",
    title: "Sleep Coach",
    subtitle: "A plan for better sleep",
    description: "AI-generated personalised sleep improvement plan based on your habits and schedule.",
    icon: "nights-stay",
    color: "#5C6BC0",
    category: "medical",
    route: "/sleep-coach",
    badge: "AI",
    available: true,
  },
  {
    id: "pre-consultation",
    title: "Pre-Consultation",
    subtitle: "Prepare for your appointment",
    description: "Organise your symptoms, history, and questions before seeing your doctor.",
    icon: "assignment",
    color: "#E0A800",
    category: "medical",
    route: "/pre-consultation",
    badge: "AI",
    available: true,
  },
  {
    id: "sleep-sounds",
    title: "Sleep Sounds",
    subtitle: "Gentle sounds for rest",
    description: "Curated ambient sounds to help you fall asleep and stay asleep naturally.",
    icon: "bedtime",
    color: "#7C5DB8",
    category: "medical",
    route: "/sleep-sounds",
    available: true,
  },
  {
    id: "emotion-tracker",
    title: "Emotion Tracker",
    subtitle: "Map how you feel",
    description: "Track emotions beyond basic moods using a detailed emotion wheel and trend analysis.",
    icon: "mood",
    color: "#E07A5F",
    category: "medical",
    route: "/mood-insights",
    badge: "New",
    available: true,
  },

  // ── Mindfulness ───────────────────────────────────────────────────
  {
    id: "breathing",
    title: "Breathing Coach",
    subtitle: "Box breathing in 4 minutes",
    description: "Guided box breathing to activate your calm response instantly, anywhere.",
    icon: "air",
    color: "#3A7BD5",
    category: "mindfulness",
    route: "/breathing",
    badge: "Popular",
    available: true,
  },
  {
    id: "meditation",
    title: "Guided Meditation",
    subtitle: "Structured calm",
    description: "Guided meditation sessions for focus, sleep, anxiety, and daily grounding.",
    icon: "self-improvement",
    color: "#6FCF97",
    category: "mindfulness",
    route: "/meditation",
    available: true,
  },
  {
    id: "mindfulness",
    title: "Mindfulness Timer",
    subtitle: "Present-moment awareness",
    description: "Simple mindfulness practice with interval bells and session history.",
    icon: "timer",
    color: "#5C6BC0",
    category: "mindfulness",
    route: "/breathing",
    available: true,
  },
  {
    id: "cognitive-reframe",
    title: "Cognitive Reframe",
    subtitle: "See it differently",
    description: "Transform catastrophic thinking into balanced, realistic perspectives step by step.",
    icon: "cached",
    color: "#7C5DB8",
    category: "mindfulness",
    route: "/cbt",
    badge: "AI",
    available: true,
  },
  {
    id: "self-care",
    title: "Self-Care Planner",
    subtitle: "Your personal care plan",
    description: "Build a sustainable self-care routine tailored to your lifestyle and goals.",
    icon: "spa",
    color: "#6FCF97",
    category: "mindfulness",
    route: "/gratitude",
    badge: "New",
    available: true,
  },
];
