export interface Doctor {
  id: string;
  name: string;
  title: string;
  gender: "F" | "M";
  specialty: string;
  county: string;
  facility: string;
  hospitalAddress: string;
  phone: string;
  email: string;
  yearsExperience: number;
  patientsServed: number;
  languages: string[];
  education: string[];
  certifications: string[];
  awards?: string[];
  bio: string;
  rating: number;
  reviews: number;
  consultationFee: number;
  telehealth: boolean;
  acceptsInsurance: boolean;
  availableDays: string[];
  availableSlots: string[];
}

export const TIME_SLOTS = [
  "08:00",
  "09:00",
  "10:00",
  "11:00",
  "13:00",
  "14:00",
  "15:00",
  "16:00",
];

export const DOCTORS: Doctor[] = [
  {
    id: "dr-cooper",
    name: "Dr. Aminata Cooper",
    title: "MD, MPH",
    gender: "F",
    specialty: "mental-health",
    county: "montserrado",
    facility: "JFK Memorial Medical Center",
    hospitalAddress: "21st Street, Sinkor, Monrovia",
    phone: "+231 770 555 101",
    email: "a.cooper@jfkmedical.lr",
    yearsExperience: 12,
    patientsServed: 3200,
    languages: ["English", "Bassa"],
    education: [
      "MD — A. M. Dogliotti College of Medicine, University of Liberia",
      "MPH (Mental Health) — University of Ghana",
    ],
    certifications: ["WHO mhGAP Certified", "Trauma-Informed Care (Carter Center)"],
    awards: ["Carter Center Mental Health Fellow, 2019"],
    bio: "Clinical psychiatrist focused on anxiety, depression, and trauma support across Liberia.",
    rating: 4.9,
    reviews: 184,
    consultationFee: 25,
    telehealth: true,
    acceptsInsurance: true,
    availableDays: ["Mon", "Tue", "Wed", "Thu"],
    availableSlots: ["09:00", "10:00", "11:00", "14:00"],
  },
  {
    id: "dr-sirleaf",
    name: "Dr. Joseph Sirleaf",
    title: "MD",
    gender: "M",
    specialty: "general",
    county: "montserrado",
    facility: "Redemption Hospital",
    hospitalAddress: "New Kru Town, Bushrod Island, Monrovia",
    phone: "+231 776 555 102",
    email: "j.sirleaf@redemption.lr",
    yearsExperience: 8,
    patientsServed: 2400,
    languages: ["English"],
    education: ["MD — A. M. Dogliotti College of Medicine"],
    certifications: ["BLS / ACLS Certified"],
    bio: "Family physician offering everyday care, screenings, and follow-ups.",
    rating: 4.7,
    reviews: 142,
    consultationFee: 18,
    telehealth: true,
    acceptsInsurance: true,
    availableDays: ["Mon", "Wed", "Fri"],
    availableSlots: ["08:00", "09:00", "13:00", "15:00"],
  },
  {
    id: "dr-toe",
    name: "Dr. Martha Toe",
    title: "MD, FWACS",
    gender: "F",
    specialty: "obgyn",
    county: "montserrado",
    facility: "John F. Kennedy Maternity Center",
    hospitalAddress: "Tubman Boulevard, Sinkor, Monrovia",
    phone: "+231 770 555 103",
    email: "m.toe@jfkmaternity.lr",
    yearsExperience: 15,
    patientsServed: 5800,
    languages: ["English", "Kpelle"],
    education: [
      "MD — University of Liberia",
      "Fellowship — West African College of Surgeons (OB/GYN)",
    ],
    certifications: ["FIGO Member", "Emergency Obstetric Care"],
    awards: ["Best Maternal Outcomes — JFK, 2022"],
    bio: "OB/GYN supporting maternal health, family planning, and women's wellness.",
    rating: 4.9,
    reviews: 220,
    consultationFee: 28,
    telehealth: false,
    acceptsInsurance: true,
    availableDays: ["Tue", "Thu", "Sat"],
    availableSlots: ["09:00", "10:00", "11:00", "14:00", "15:00"],
  },
  {
    id: "dr-koffa",
    name: "Dr. Emmanuel Koffa",
    title: "MD",
    gender: "M",
    specialty: "mental-health",
    county: "nimba",
    facility: "Ganta United Methodist Hospital",
    hospitalAddress: "Ganta City, Nimba County",
    phone: "+231 776 555 104",
    email: "e.koffa@gantahospital.lr",
    yearsExperience: 10,
    patientsServed: 1900,
    languages: ["English", "Mano"],
    education: [
      "MD — University of Liberia",
      "Diploma in Mental Health — Carter Center Liberia",
    ],
    certifications: ["WHO mhGAP Certified"],
    bio: "Mental health specialist focusing on rural community care.",
    rating: 4.8,
    reviews: 98,
    consultationFee: 20,
    telehealth: true,
    acceptsInsurance: false,
    availableDays: ["Mon", "Tue", "Fri"],
    availableSlots: ["08:00", "10:00", "13:00", "16:00"],
  },
  {
    id: "dr-doe",
    name: "Dr. Patience Doe",
    title: "MD",
    gender: "F",
    specialty: "pediatrics",
    county: "nimba",
    facility: "Saclepea Comprehensive Health Center",
    hospitalAddress: "Saclepea District, Nimba County",
    phone: "+231 770 555 105",
    email: "p.doe@saclepeahealth.lr",
    yearsExperience: 7,
    patientsServed: 1600,
    languages: ["English"],
    education: ["MD — A. M. Dogliotti College of Medicine"],
    certifications: ["EPI / Vaccination Specialist"],
    bio: "Pediatrician dedicated to child wellness and immunization.",
    rating: 4.6,
    reviews: 61,
    consultationFee: 15,
    telehealth: false,
    acceptsInsurance: true,
    availableDays: ["Wed", "Thu", "Fri"],
    availableSlots: ["09:00", "10:00", "11:00", "14:00"],
  },
  {
    id: "dr-flomo",
    name: "Dr. Samuel Flomo",
    title: "MD",
    gender: "M",
    specialty: "general",
    county: "bong",
    facility: "Phebe Hospital",
    hospitalAddress: "Suakoko, Bong County",
    phone: "+231 776 555 106",
    email: "s.flomo@phebehospital.lr",
    yearsExperience: 14,
    patientsServed: 4200,
    languages: ["English", "Kpelle"],
    education: ["MD — University of Liberia", "Diploma — Family Medicine"],
    certifications: ["BLS / ACLS"],
    awards: ["Phebe Service Award, 2021"],
    bio: "General practitioner with deep experience in rural primary care.",
    rating: 4.7,
    reviews: 156,
    consultationFee: 18,
    telehealth: true,
    acceptsInsurance: true,
    availableDays: ["Mon", "Tue", "Wed", "Thu", "Fri"],
    availableSlots: ["08:00", "09:00", "10:00", "13:00", "14:00"],
  },
  {
    id: "dr-yangbe",
    name: "Dr. Grace Yangbe",
    title: "MD",
    gender: "F",
    specialty: "mental-health",
    county: "bong",
    facility: "Phebe Mental Health Unit",
    hospitalAddress: "Suakoko, Bong County",
    phone: "+231 770 555 107",
    email: "g.yangbe@phebehospital.lr",
    yearsExperience: 9,
    patientsServed: 1400,
    languages: ["English", "Kpelle"],
    education: ["MD — University of Liberia", "Mental Health Diploma — Carter Center"],
    certifications: ["WHO mhGAP", "Family Counseling"],
    bio: "Mental health practitioner supporting youth and family counseling.",
    rating: 4.8,
    reviews: 87,
    consultationFee: 20,
    telehealth: true,
    acceptsInsurance: false,
    availableDays: ["Tue", "Thu"],
    availableSlots: ["09:00", "11:00", "14:00", "15:00"],
  },
  {
    id: "dr-kollie",
    name: "Dr. Mohammed Kollie",
    title: "MD",
    gender: "M",
    specialty: "internal",
    county: "lofa",
    facility: "Tellewoyan Memorial Hospital",
    hospitalAddress: "Voinjama, Lofa County",
    phone: "+231 776 555 108",
    email: "m.kollie@tellewoyan.lr",
    yearsExperience: 11,
    patientsServed: 2100,
    languages: ["English", "Loma"],
    education: ["MD — University of Liberia", "Diploma — Internal Medicine, Ghana"],
    certifications: ["Hypertension & Diabetes Care"],
    bio: "Internal medicine specialist with focus on chronic disease care.",
    rating: 4.6,
    reviews: 74,
    consultationFee: 22,
    telehealth: true,
    acceptsInsurance: true,
    availableDays: ["Mon", "Wed", "Fri"],
    availableSlots: ["08:00", "10:00", "13:00", "15:00"],
  },
  {
    id: "dr-massaquoi",
    name: "Dr. Fatu Massaquoi",
    title: "MD",
    gender: "F",
    specialty: "general",
    county: "lofa",
    facility: "Foya Borma Hospital",
    hospitalAddress: "Foya District, Lofa County",
    phone: "+231 770 555 109",
    email: "f.massaquoi@foyaborma.lr",
    yearsExperience: 6,
    patientsServed: 1100,
    languages: ["English"],
    education: ["MD — A. M. Dogliotti College of Medicine"],
    certifications: ["BLS Certified"],
    bio: "General doctor serving northern communities of Liberia.",
    rating: 4.5,
    reviews: 49,
    consultationFee: 16,
    telehealth: false,
    acceptsInsurance: false,
    availableDays: ["Mon", "Tue", "Thu"],
    availableSlots: ["09:00", "10:00", "13:00"],
  },
  {
    id: "dr-tarpeh",
    name: "Dr. James Tarpeh",
    title: "MD, FWACP",
    gender: "M",
    specialty: "cardiology",
    county: "grand-bassa",
    facility: "Liberia Government Hospital, Buchanan",
    hospitalAddress: "Buchanan City, Grand Bassa County",
    phone: "+231 776 555 110",
    email: "j.tarpeh@lgh-buchanan.lr",
    yearsExperience: 16,
    patientsServed: 3700,
    languages: ["English", "Bassa"],
    education: [
      "MD — University of Liberia",
      "Fellowship — West African College of Physicians (Cardiology)",
    ],
    certifications: ["Echocardiography", "Hypertension Specialist"],
    awards: ["Excellence in Cardiac Care, 2020"],
    bio: "Cardiologist focusing on hypertension and heart disease management.",
    rating: 4.9,
    reviews: 203,
    consultationFee: 35,
    telehealth: true,
    acceptsInsurance: true,
    availableDays: ["Tue", "Thu"],
    availableSlots: ["09:00", "10:00", "14:00", "15:00"],
  },
  {
    id: "dr-quoi",
    name: "Dr. Hannah Quoi",
    title: "MD",
    gender: "F",
    specialty: "pediatrics",
    county: "grand-bassa",
    facility: "Buchanan Health Center",
    hospitalAddress: "Buchanan City, Grand Bassa County",
    phone: "+231 770 555 111",
    email: "h.quoi@buchananhealth.lr",
    yearsExperience: 5,
    patientsServed: 950,
    languages: ["English", "Bassa"],
    education: ["MD — A. M. Dogliotti College of Medicine"],
    certifications: ["EPI / Newborn Resuscitation"],
    bio: "Pediatric care for newborns and children.",
    rating: 4.6,
    reviews: 38,
    consultationFee: 14,
    telehealth: false,
    acceptsInsurance: true,
    availableDays: ["Mon", "Wed", "Fri"],
    availableSlots: ["09:00", "10:00", "11:00", "14:00"],
  },
  {
    id: "dr-johnson",
    name: "Dr. Ruth Johnson",
    title: "MD",
    gender: "F",
    specialty: "obgyn",
    county: "margibi",
    facility: "C.H. Rennie Hospital",
    hospitalAddress: "Kakata, Margibi County",
    phone: "+231 776 555 112",
    email: "r.johnson@chrennie.lr",
    yearsExperience: 12,
    patientsServed: 3100,
    languages: ["English"],
    education: ["MD — University of Liberia", "Diploma — Reproductive Health"],
    certifications: ["FIGO Member", "Family Planning Specialist"],
    bio: "Women's health and maternal care specialist.",
    rating: 4.8,
    reviews: 119,
    consultationFee: 24,
    telehealth: true,
    acceptsInsurance: true,
    availableDays: ["Mon", "Tue", "Wed", "Fri"],
    availableSlots: ["08:00", "10:00", "13:00", "15:00"],
  },
  {
    id: "dr-kanneh",
    name: "Dr. Ibrahim Kanneh",
    title: "MD",
    gender: "M",
    specialty: "general",
    county: "margibi",
    facility: "Kakata Health Center",
    hospitalAddress: "Kakata, Margibi County",
    phone: "+231 770 555 113",
    email: "i.kanneh@kakatahealth.lr",
    yearsExperience: 9,
    patientsServed: 1800,
    languages: ["English"],
    education: ["MD — A. M. Dogliotti College of Medicine"],
    certifications: ["Telehealth Certified", "BLS"],
    bio: "Primary care physician with telehealth experience.",
    rating: 4.7,
    reviews: 81,
    consultationFee: 18,
    telehealth: true,
    acceptsInsurance: false,
    availableDays: ["Tue", "Thu", "Sat"],
    availableSlots: ["09:00", "11:00", "14:00", "16:00"],
  },
  {
    id: "dr-vah",
    name: "Dr. Korpo Vah",
    title: "MD",
    gender: "F",
    specialty: "mental-health",
    county: "bomi",
    facility: "Liberia Government Hospital, Tubmanburg",
    hospitalAddress: "Tubmanburg, Bomi County",
    phone: "+231 776 555 114",
    email: "k.vah@lgh-tubmanburg.lr",
    yearsExperience: 8,
    patientsServed: 1300,
    languages: ["English", "Vai"],
    education: ["MD — University of Liberia", "Mental Health Diploma — Carter Center"],
    certifications: ["WHO mhGAP", "Trauma Counseling"],
    bio: "Counselor and mental health practitioner serving western Liberia.",
    rating: 4.7,
    reviews: 53,
    consultationFee: 18,
    telehealth: true,
    acceptsInsurance: true,
    availableDays: ["Wed", "Fri"],
    availableSlots: ["09:00", "10:00", "13:00", "14:00"],
  },
  {
    id: "dr-bestman",
    name: "Dr. Daniel Bestman",
    title: "MD",
    gender: "M",
    specialty: "general",
    county: "bomi",
    facility: "Tubmanburg Clinic",
    hospitalAddress: "Tubmanburg, Bomi County",
    phone: "+231 770 555 115",
    email: "d.bestman@tubmanburgclinic.lr",
    yearsExperience: 6,
    patientsServed: 900,
    languages: ["English"],
    education: ["MD — A. M. Dogliotti College of Medicine"],
    certifications: ["BLS Certified"],
    bio: "General medicine and acute care.",
    rating: 4.5,
    reviews: 32,
    consultationFee: 15,
    telehealth: false,
    acceptsInsurance: false,
    availableDays: ["Mon", "Wed"],
    availableSlots: ["08:00", "09:00", "13:00"],
  },
  {
    id: "dr-sherman",
    name: "Dr. Esther Sherman",
    title: "MD",
    gender: "F",
    specialty: "obgyn",
    county: "grand-cape-mount",
    facility: "St. Timothy Government Hospital",
    hospitalAddress: "Robertsport, Grand Cape Mount County",
    phone: "+231 776 555 116",
    email: "e.sherman@sttimothy.lr",
    yearsExperience: 13,
    patientsServed: 2700,
    languages: ["English", "Vai"],
    education: ["MD — University of Liberia", "Diploma — OB/GYN, Ghana"],
    certifications: ["Maternal Health Specialist"],
    bio: "Maternal health and women's wellness.",
    rating: 4.8,
    reviews: 96,
    consultationFee: 22,
    telehealth: true,
    acceptsInsurance: true,
    availableDays: ["Mon", "Thu"],
    availableSlots: ["09:00", "10:00", "14:00", "15:00"],
  },
  {
    id: "dr-kromah",
    name: "Dr. Augustus Kromah",
    title: "MD",
    gender: "M",
    specialty: "general",
    county: "grand-cape-mount",
    facility: "Robertsport Health Center",
    hospitalAddress: "Robertsport, Grand Cape Mount County",
    phone: "+231 770 555 117",
    email: "a.kromah@robertsporthealth.lr",
    yearsExperience: 7,
    patientsServed: 1200,
    languages: ["English"],
    education: ["MD — A. M. Dogliotti College of Medicine"],
    certifications: ["BLS"],
    bio: "General physician serving the coastal communities.",
    rating: 4.6,
    reviews: 41,
    consultationFee: 16,
    telehealth: false,
    acceptsInsurance: false,
    availableDays: ["Tue", "Wed", "Fri"],
    availableSlots: ["08:00", "10:00", "13:00", "15:00"],
  },
  {
    id: "dr-zogar",
    name: "Dr. Anthony Zogar",
    title: "MD",
    gender: "M",
    specialty: "general",
    county: "gbarpolu",
    facility: "Bopolu Health Center",
    hospitalAddress: "Bopolu City, Gbarpolu County",
    phone: "+231 776 555 118",
    email: "a.zogar@bopoluhealth.lr",
    yearsExperience: 9,
    patientsServed: 1500,
    languages: ["English"],
    education: ["MD — University of Liberia"],
    certifications: ["Rural Outreach Care"],
    bio: "Rural medicine and outreach care.",
    rating: 4.5,
    reviews: 28,
    consultationFee: 15,
    telehealth: false,
    acceptsInsurance: false,
    availableDays: ["Mon", "Wed"],
    availableSlots: ["09:00", "10:00", "13:00"],
  },
  {
    id: "dr-mulbah",
    name: "Dr. Beatrice Mulbah",
    title: "MD",
    gender: "F",
    specialty: "pediatrics",
    county: "gbarpolu",
    facility: "Gbarpolu Community Clinic",
    hospitalAddress: "Bopolu City, Gbarpolu County",
    phone: "+231 770 555 119",
    email: "b.mulbah@gbarpoluclinic.lr",
    yearsExperience: 6,
    patientsServed: 850,
    languages: ["English"],
    education: ["MD — A. M. Dogliotti College of Medicine"],
    certifications: ["EPI Certified"],
    bio: "Children's primary care.",
    rating: 4.5,
    reviews: 22,
    consultationFee: 14,
    telehealth: false,
    acceptsInsurance: true,
    availableDays: ["Tue", "Fri"],
    availableSlots: ["09:00", "11:00", "14:00"],
  },
  {
    id: "dr-paye",
    name: "Dr. Stephen Paye",
    title: "MD",
    gender: "M",
    specialty: "general",
    county: "river-cess",
    facility: "Cestos City Health Center",
    hospitalAddress: "Cestos City, River Cess County",
    phone: "+231 776 555 120",
    email: "s.paye@cestoshealth.lr",
    yearsExperience: 10,
    patientsServed: 1700,
    languages: ["English", "Bassa"],
    education: ["MD — University of Liberia"],
    certifications: ["BLS Certified"],
    bio: "General doctor serving River Cess county.",
    rating: 4.7,
    reviews: 44,
    consultationFee: 16,
    telehealth: true,
    acceptsInsurance: false,
    availableDays: ["Mon", "Wed", "Fri"],
    availableSlots: ["08:00", "10:00", "13:00", "15:00"],
  },
  {
    id: "dr-blee",
    name: "Dr. Leona Blee",
    title: "MD",
    gender: "F",
    specialty: "internal",
    county: "sinoe",
    facility: "F.J. Grante Hospital",
    hospitalAddress: "Greenville, Sinoe County",
    phone: "+231 770 555 121",
    email: "l.blee@fjgrante.lr",
    yearsExperience: 11,
    patientsServed: 2200,
    languages: ["English"],
    education: [
      "MD — University of Liberia",
      "Diploma — Internal Medicine, Ghana",
    ],
    certifications: ["Diabetes Care Specialist"],
    bio: "Internal medicine specialist focusing on chronic care.",
    rating: 4.7,
    reviews: 58,
    consultationFee: 22,
    telehealth: true,
    acceptsInsurance: true,
    availableDays: ["Tue", "Thu"],
    availableSlots: ["09:00", "11:00", "14:00"],
  },
  {
    id: "dr-wreh",
    name: "Dr. Augustine Wreh",
    title: "MD",
    gender: "M",
    specialty: "general",
    county: "sinoe",
    facility: "Greenville Health Center",
    hospitalAddress: "Greenville, Sinoe County",
    phone: "+231 776 555 122",
    email: "a.wreh@greenvillehealth.lr",
    yearsExperience: 7,
    patientsServed: 1200,
    languages: ["English"],
    education: ["MD — A. M. Dogliotti College of Medicine"],
    certifications: ["BLS Certified"],
    bio: "Primary care for southeast Liberia.",
    rating: 4.5,
    reviews: 33,
    consultationFee: 15,
    telehealth: false,
    acceptsInsurance: false,
    availableDays: ["Mon", "Wed", "Fri"],
    availableSlots: ["08:00", "10:00", "13:00"],
  },
  {
    id: "dr-tah",
    name: "Dr. Mary Tah",
    title: "MD",
    gender: "F",
    specialty: "mental-health",
    county: "grand-gedeh",
    facility: "Martha Tubman Memorial Hospital",
    hospitalAddress: "Zwedru, Grand Gedeh County",
    phone: "+231 770 555 123",
    email: "m.tah@marthatubman.lr",
    yearsExperience: 9,
    patientsServed: 1400,
    languages: ["English", "Krahn"],
    education: ["MD — University of Liberia", "Mental Health Diploma — Carter Center"],
    certifications: ["WHO mhGAP", "Adolescent Counseling"],
    bio: "Mental health counselor for southeastern Liberia.",
    rating: 4.8,
    reviews: 47,
    consultationFee: 20,
    telehealth: true,
    acceptsInsurance: false,
    availableDays: ["Tue", "Thu"],
    availableSlots: ["09:00", "11:00", "14:00", "15:00"],
  },
  {
    id: "dr-saydee",
    name: "Dr. Boakai Saydee",
    title: "MD",
    gender: "M",
    specialty: "general",
    county: "grand-gedeh",
    facility: "Zwedru Government Hospital",
    hospitalAddress: "Zwedru, Grand Gedeh County",
    phone: "+231 776 555 124",
    email: "b.saydee@zwedrugov.lr",
    yearsExperience: 12,
    patientsServed: 2600,
    languages: ["English"],
    education: ["MD — University of Liberia"],
    certifications: ["BLS / ACLS"],
    bio: "General practitioner across rural southeast.",
    rating: 4.6,
    reviews: 52,
    consultationFee: 17,
    telehealth: false,
    acceptsInsurance: true,
    availableDays: ["Mon", "Wed", "Fri"],
    availableSlots: ["08:00", "10:00", "13:00", "15:00"],
  },
  {
    id: "dr-davis",
    name: "Dr. Janet Davis",
    title: "MD",
    gender: "F",
    specialty: "general",
    county: "river-gee",
    facility: "Fish Town Health Center",
    hospitalAddress: "Fish Town, River Gee County",
    phone: "+231 770 555 125",
    email: "j.davis@fishtownhealth.lr",
    yearsExperience: 6,
    patientsServed: 900,
    languages: ["English", "Grebo"],
    education: ["MD — A. M. Dogliotti College of Medicine"],
    certifications: ["Community Health Specialist"],
    bio: "Community health and primary care.",
    rating: 4.5,
    reviews: 24,
    consultationFee: 14,
    telehealth: false,
    acceptsInsurance: false,
    availableDays: ["Mon", "Tue", "Wed"],
    availableSlots: ["09:00", "10:00", "13:00"],
  },
  {
    id: "dr-yancy",
    name: "Dr. Robert Yancy",
    title: "MD, FWACS",
    gender: "M",
    specialty: "obgyn",
    county: "maryland",
    facility: "J.J. Dossen Memorial Hospital",
    hospitalAddress: "Harper, Maryland County",
    phone: "+231 776 555 126",
    email: "r.yancy@jjdossen.lr",
    yearsExperience: 14,
    patientsServed: 3300,
    languages: ["English", "Grebo"],
    education: [
      "MD — University of Liberia",
      "Fellowship — West African College of Surgeons",
    ],
    certifications: ["Emergency Obstetric Care"],
    awards: ["Best Service Award, J.J. Dossen, 2021"],
    bio: "Maternal and women's health specialist.",
    rating: 4.8,
    reviews: 88,
    consultationFee: 22,
    telehealth: true,
    acceptsInsurance: true,
    availableDays: ["Mon", "Wed", "Fri"],
    availableSlots: ["09:00", "10:00", "11:00", "14:00"],
  },
  {
    id: "dr-nagbe",
    name: "Dr. Albert Nagbe",
    title: "MD",
    gender: "M",
    specialty: "mental-health",
    county: "maryland",
    facility: "Harper Mental Health Outreach",
    hospitalAddress: "Harper, Maryland County",
    phone: "+231 770 555 127",
    email: "a.nagbe@harpermental.lr",
    yearsExperience: 7,
    patientsServed: 1100,
    languages: ["English", "Grebo"],
    education: ["MD — University of Liberia", "Counseling Diploma — Carter Center"],
    certifications: ["WHO mhGAP", "Trauma-Informed Care"],
    bio: "Counseling support for trauma and stress.",
    rating: 4.7,
    reviews: 36,
    consultationFee: 18,
    telehealth: true,
    acceptsInsurance: false,
    availableDays: ["Tue", "Thu"],
    availableSlots: ["09:00", "11:00", "14:00"],
  },
  {
    id: "dr-toe-jr",
    name: "Dr. Williamette Toe",
    title: "MD",
    gender: "F",
    specialty: "general",
    county: "grand-kru",
    facility: "Barclayville Health Center",
    hospitalAddress: "Barclayville, Grand Kru County",
    phone: "+231 776 555 128",
    email: "w.toe@barclayvillehealth.lr",
    yearsExperience: 8,
    patientsServed: 1400,
    languages: ["English"],
    education: ["MD — A. M. Dogliotti College of Medicine"],
    certifications: ["BLS Certified", "Community Outreach"],
    bio: "Primary care and outreach for Grand Kru.",
    rating: 4.6,
    reviews: 31,
    consultationFee: 15,
    telehealth: false,
    acceptsInsurance: true,
    availableDays: ["Mon", "Wed"],
    availableSlots: ["09:00", "10:00", "13:00", "15:00"],
  },
];
